### ISSUE TITLE
Compile and distribute persistent files

### ISSUE THREAD

**Issue by TAKeanice** [SPUNIKNSS15/SPUNIKNSS15_GraphInformation#3]
to speed up compilation time for the others.

Sprint: SPUNIKNSS15/SPUNIKNSS15_Organization#19

**Comment by owdmn** [comment]
Ran into the following compilation errors:
- teo.isgci/appl/iq/IQparser.java: package mouse.runtime does not exist
- teo.isgci/appl/deducer/Generate.java: package gnu.getopt does not exist

Advise adding .jar files of the missing dependencies to our repo

**Comment by owdmn** [comment]
Missing class IQParser, used in teo.isgci/iq/IQ.java
https://github.com/firewarrior/GraphIT/blob/master/teo/teo/isgci/iq/IQParser.java
This might be a possible fix.

**Comment by owdmn** [comment]
Tried running FindISG on data/smallgraphs.xml
Result:

---

Digraph is made. Starting to add big smallmembers
Exception in thread "main" java.io.IOException: Cannot run program "vf": error=2, No such file or directory
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
    at java.lang.Runtime.exec(Runtime.java:620)
    at java.lang.Runtime.exec(Runtime.java:450)
    at java.lang.Runtime.exec(Runtime.java:347)
    at teo.isgci.appl.FindISG.isSubgraphVF(FindISG.java:607)
    at teo.isgci.appl.FindISG.addBigSmallmembers(FindISG.java:509)
    at teo.isgci.appl.FindISG.main(FindISG.java:183)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.io.IOException: error=2, No such file or directory
    at java.lang.UNIXProcess.forkAndExec(Native Method)
    at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
    at java.lang.ProcessImpl.start(ProcessImpl.java:134)
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
    ... 11 more

Process finished with exit code 1

---

We'll have to ask the customer to provide vl, can't find the external component after hours of searching...

**Comment by TAKeanice** [comment]
New Sprint: https://github.com/SPUNIKNSS15/SPUNIKNSS15_Organization/issues/20

**Comment by TAKeanice** [comment]
Olli and me both managed to compile the program and run it on the included smallgraphs.xml. Output can be found in a future commit
